# Custom symbols used for patches.
[[section]]
name = "ABSOLUTE_SYMS"
vram = 0x00000000
size = 0x0

symbols = [
    # Alternate references to symbols that would otherwise be relocated
    { name = "Setup_Init_NORELOCATE", vram = 0x80173338 }, # Not relocatable, but here for uniformity with the other gamestate funcs
    { name = "MapSelect_Init_NORELOCATE", vram = 0x80801B4C },
    { name = "ConsoleLogo_Init_NORELOCATE", vram = 0x8080074C },
    { name = "Play_Init_NORELOCATE", vram = 0x8016A2C8 },
    { name = "TitleSetup_Init_NORELOCATE", vram = 0x80803F30 },
    { name = "FileSelect_Init_NORELOCATE", vram = 0x80813C98 },
    { name = "DayTelop_Init_NORELOCATE", vram = 0x80815820 },
]
