# Custom symbols used for patches.
[[section]]
name = "ABSOLUTE_SYMS"
vram = 0x00000000
size = 0x0

symbols = [
    # Alternate references to symbols that would otherwise be relocated
    { name = "Setup_Init_NORELOCATE", vram = 0x80173338 }, # Not relocatable, but here for uniformity with the other gamestate funcs
    { name = "MapSelect_Init_NORELOCATE", vram = 0x80801B4C },
    { name = "ConsoleLogo_Init_NORELOCATE", vram = 0x8080074C },
    { name = "Play_Init_NORELOCATE", vram = 0x8016A2C8 },
    { name = "TitleSetup_Init_NORELOCATE", vram = 0x80803F30 },
    { name = "FileSelect_Init_NORELOCATE", vram = 0x80813C98 },
    { name = "DayTelop_Init_NORELOCATE", vram = 0x80815820 },
]

[[section]]
name = "..ovl_En_Hg"
rom = 0x01034170
vram = 0x80BCF1D0
size = 0x10E0

symbols = [
    { name = "sPamelasFatherGibdoAnimationInfo", vram = 0x80bd0008 },
]

[[section]]
name = "..ovl_En_Hgo"
rom = 0x01035250
vram = 0x80BD02B0
size = 0xF30

symbols = [
    { name = "sPamelasFatherHumanAnimationInfo", vram = 0x80BD0EA0 },
]

[[section]]
name = "..ovl_En_Pamera"
rom = 0x0103D250
vram = 0x80BD82B0
size = 0x2780

symbols = [
    { name = "sPamelaAnimationInfo", vram = 0x80BDA4B8 },
]
